from typing import Optional, List, Dict

from fastapi import Request, HTTPException
from fastapi.responses import RedirectResponse, JSONResponse
from starlette.middleware.base import BaseHTTPMiddleware

from oidc_auth.controller import OIDCController
from oidc_auth.types import OIDCSettings




# --- 2. The Middleware ---
class OIDCAuthMiddleware(BaseHTTPMiddleware):
    """
    Starlette middleware for OpenID Connect (OIDC) authentication and session management.

    This middleware intercepts incoming HTTP requests to manage the OIDC authentication
    flow. It integrates with an `OIDCController` to handle login redirects,
    authorization code callbacks, and logout operations.

    It also provides protection for application routes:
    - Unauthenticated users attempting to access protected routes are redirected
      to the login page.
    - API endpoints (paths starting with "/api") return a 401 Unauthorized response
      for unauthenticated access.
    - Specific paths can be whitelisted as public, bypassing authentication.

    Attributes:
        app (ASGIApp): The ASGI application instance.
        controller (OIDCController): An instance of OIDCController to handle OIDC logic.
        public_paths (List[str]): A list of URL path prefixes that should be publicly
                                  accessible without authentication.
    """
    def __init__(self, app, controller: OIDCController, public_paths: List[str] = None):
        """
        Initializes the OIDCAuthMiddleware.

        Args:
            app (ASGIApp): The ASGI application instance to be wrapped by the middleware.
            controller (OIDCController): An instance of the OIDCController responsible
                                         for handling OIDC protocol-specific logic.
            public_paths (List[str], optional): A list of URL path prefixes that
                                                should be accessible without authentication.
                                                Defaults to an empty list.
        """
        super().__init__(app)
        self.controller = controller
        self.public_paths = public_paths or []

    async def dispatch(self, request: Request, call_next):
        """
        The entry point for processing incoming requests through the middleware.

        This method performs the following steps:
        1. Resolves session information from cookies and attaches user data to `request.state.user`.
        2. Intercepts OIDC-specific routes ("/login", "/oidc/callback", "/oidc/logout")
           and delegates their handling to the `OIDCController`.
        3. Applies protection logic:
           - Allows requests for `public_paths` to proceed without authentication.
           - Redirects unauthenticated users from protected web routes to "/login".
           - Returns a 401 Unauthorized JSON response for unauthenticated access
             to protected API routes (those starting with "/api").
        4. Passes the request to the next middleware or the application endpoint
           if authentication checks pass or the path is public.

        Args:
            request (Request): The incoming FastAPI/Starlette request object.
            call_next (Callable): The next callable in the middleware stack.

        Returns:
            Response: The response generated by an OIDC route, a redirect to
                      login, an unauthorized JSON response, or the response from
                      the subsequent middleware/application.
        """
        # 1. Resolve Session
        session_id = request.cookies.get("session_id")
        request.state.user = None
        
        if session_id and session_id in self.controller.session_store:
            request.state.user = self.controller.session_store[session_id].get("user")

        # 2. Handle OIDC Routes via Controller
        path = request.url.path
        if path == "/login":
            return await self.controller.login(request)
        if path == "/oidc/callback":
            return await self.controller.callback(request)
        if path == "/oidc/logout":
            return await self.controller.logout(request)

        # 3. Protection Logic
        if any(path.startswith(p) for p in self.public_paths):
            return await call_next(request)

        if not request.state.user:
            if path.startswith("/api"):
                 return JSONResponse({"error": "Unauthorized"}, status_code=401)
            return RedirectResponse(url="/login")

        return await call_next(request)
